applications:
  - name: django-app
    namespace: default
    project: default
    source:
      repoURL: https://github.com/Malicious1986/devops.git
      path: charts/django-app
      targetRevision: main
      helm:
        valueFiles:
          - values.yaml
    destination:
      server: https://kubernetes.default.svc
      namespace: default
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

repositories:
  - name: django-app
    url: https://github.com/Malicious1986/devops.git
    username: Malicious1986
    password: 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

repoConfig:
  insecure: "true"
  enableLfs: "true"
