def ECR_REGISTRY = "460589479898.dkr.ecr.eu-west-1.amazonaws.com"
def IMAGE_NAME   = "lesson-5-ecr"
def IMAGE_TAG    = "latest"

podTemplate(
  yaml: """
apiVersion: v1
kind: Pod
spec:
  serviceAccountName: jenkins-sa
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:v1.16.0-debug
    imagePullPolicy: Always
    command: ['sleep']
    args: ['99d']
"""
) {
  node(POD_LABEL) {
    checkout scm
    container('kaniko') {
      sh """
        /kaniko/executor \\
          --context \$(pwd)/django \\
          --dockerfile \$(pwd)/django/Dockerfile \\
          --destination=${ECR_REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG}
      """
    }
  }
}
