apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ .Release.Name }}-django

spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount | default 2 }}
  {{- end }}

  selector:
    matchLabels:
      app: {{ .Release.Name }}-django

  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-django

    spec:
      containers:
        - name: django

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: {{ .Values.service.port }}

          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-config

            - secretRef:
                name: {{ .Release.Name }}-secret

          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"

          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.port }}
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.port }}
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3